### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ydennisy** [ydennisy/kg1#20]
# Roadmap

A simple catch all issue for roadmap items.

- [ ] Improve the way hackernews links are handled: make two KG entries, one for the target link and one for the discussion thread.
- [ ] Start to connect documents: this can be done by extracting entities and created an edge between docs based on the number of shared entities. One complication is to figure out a normalisation strategy, so large docs are not more "strongly" linked to all other docs.
- [ ] Serve the homepage as a static page: once this is figured out we can also start to serve more pages as static pages - for example all document node pages. Another idea is to expose past Q&A as static docs.
- [ ] Add IP rate limiting, and swap from `429` to another status code to differentiate GCP cold start from too many requests from the same client or tokens exhausted.
- [ ] Allow chat with document in node details view, this could look like moving back to `ask` page with the document inserted into the context.
- [ ] Improve the way sources are shown in the UI after the `ask`, mainly ensure this is consistent in terms of formatting.
- [ ] Index many more sites and in the process fix bugs related to how sites are crawled, embedded and indexed.
- [ ] Move the indexation process to run in the background, it currently takes too long, users should not need to wait.
- [ ] Consider adding a feed page showing all recently indexed documents, their state etc.
- [ ] Work out the admin features of re-processing existing URLs, to allow for improvements to things like chunking strategies. To facilitate a job to re-process (migrate) indexed URLs - we could add a version to each URL, to show which version of the system processed it. Another idea from this, is to treat these changes as migrations, by following the same strategies as done with SQL, i.e add a new chunking strategy to a folder and the system recognises and runs it.
- [ ] Add tests! Especially for URL indexing, and ensuring failed URLs do not take down the rest in the batch.
